# Generated by Django 6.0.4 on 2026-05-01 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type_salle', models.CharField(choices=[('amphi', 'Amphithéâtre'), ('salle', 'Salle'), ('tp', 'Salle TP'), ('info', 'Salle Informatique')], max_length=10)),
                ('capacite', models.IntegerField()),
                ('batiment', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('mathematiques', 'Mathématiques'), ('informatique', 'Informatique'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('sciences_vie', 'Sciences de la Vie'), ('sciences_terre', 'Sciences de la Terre')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_dirige', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(choices=[('assistant', 'Assistant'), ('maitre_assistant', 'Maître Assistant'), ('maitre_conf', 'Maître de Conférences'), ('professeur', 'Professeur')], max_length=30)),
                ('specialite', models.CharField(max_length=100)),
                ('date_recrutement', models.DateField(blank=True, null=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.departement')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('Doc', 'Doctorat')], max_length=5)),
                ('type_formation', models.CharField(choices=[('fondamentale', 'Fondamentale'), ('appliquee', 'Appliquée'), ('professionnelle', 'Professionnelle')], default='fondamentale', max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='administration.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(max_length=20, unique=True)),
                ('cin', models.CharField(blank=True, max_length=20, unique=True)),
                ('annee_inscription', models.IntegerField()),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('suspendu', 'Suspendu'), ('diplome', 'Diplômé'), ('abandonne', 'Abandonné')], default='inscrit', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(max_length=9)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.filiere')),
            ],
            options={
                'unique_together': {('etudiant', 'annee_universitaire')},
            },
        ),
    ]
