# Generated by Django 6.0.4 on 2026-05-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
        migrations.AddField(
            model_name='departement',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='departement',
            name='chef',
            field=models.CharField(blank=True, help_text='Nom du chef de département', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(choices=[('mathematiques', 'Mathématiques'), ('informatique', 'Informatique'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('biologie', 'Biologie'), ('geologie', 'Géologie')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='administration.departement'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='administration.filiere'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('Doc', 'Doctorat'), ('CPI1', 'Cycle Préparatoire Intégré 1'), ('CPI2', 'Cycle Préparatoire Intégré 2'), ('CI1', 'Cycle Ingénieur 1'), ('CI2', 'Cycle Ingénieur 2'), ('CI3', 'Cycle Ingénieur 3')], max_length=5),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='administration.etudiant'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='type_salle',
            field=models.CharField(choices=[('amphi', 'Amphithéâtre'), ('salle', 'Salle de Cours'), ('tp', 'Salle TP'), ('info', 'Salle Informatique')], max_length=10),
        ),
    ]
