# Generated by Django 6.0.4 on 2026-05-03 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_enseignant_user_remove_etudiant_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filiere',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='niveau',
            field=models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('Doc', 'Doctorat'), ('CPI', 'Cycle Préparatoire Intégré'), ('CI', 'Cycle Ingénieur')], max_length=5),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='type_formation',
            field=models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('cpi', 'CPI'), ('ci', 'CI')], default='licence', max_length=20),
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('niveau', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('Doc1', 'Doctorat 1'), ('Doc2', 'Doctorat 2'), ('Doc3', 'Doctorat 3'), ('CPI1', 'Cycle Préparatoire Intégré 1'), ('CPI2', 'Cycle Préparatoire Intégré 2'), ('CI1', 'Cycle Ingénieur 1'), ('CI2', 'Cycle Ingénieur 2'), ('CI3', 'Cycle Ingénieur 3')], max_length=10)),
                ('annee_universitaire', models.CharField(default='2024-2025', max_length=9)),
                ('capacite', models.IntegerField(default=30)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='administration.filiere')),
            ],
        ),
    ]
