# Generated by Django 6.0.4 on 2026-05-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_filiere_description_alter_filiere_niveau_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscription',
            options={'ordering': ['-date_inscription']},
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='valide',
        ),
        migrations.AddField(
            model_name='inscription',
            name='commentaire',
            field=models.TextField(blank=True, default='', help_text="Commentaire de l'administration"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_validation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de validation'), ('dossier_incomplet', 'Dossier incomplet'), ('frais_non_payes', 'Frais non payés'), ('validee', 'Validée'), ('suspendue', 'Suspendue'), ('annulee', 'Annulée')], default='en_attente', max_length=25),
        ),
        migrations.AddField(
            model_name='inscription',
            name='valide_par',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='annee_universitaire',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
    ]
