# Generated by Django 6.0.4 on 2026-05-01 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('credits', models.IntegerField(default=3)),
                ('coefficient', models.FloatField(default=1.0)),
                ('heures_cours', models.IntegerField(default=0)),
                ('heures_td', models.IntegerField(default=0)),
                ('heures_tp', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')])),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('type_seance', models.CharField(choices=[('cours', 'Cours'), ('td', 'TD'), ('tp', 'TP')], max_length=10)),
                ('annee_universitaire', models.CharField(max_length=9)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')])),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.enseignant')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.salle')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('justifiee', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.emploidutemps')),
            ],
            options={
                'unique_together': {('etudiant', 'seance', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_note', models.CharField(choices=[('ds', 'DS'), ('exam', 'Examen'), ('tp', 'TP'), ('expose', 'Exposé'), ('rattrapage', 'Rattrapage')], max_length=15)),
                ('note', models.FloatField()),
                ('annee_universitaire', models.CharField(max_length=9)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')])),
                ('date_saisie', models.DateField(auto_now_add=True)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.enseignant')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
            ],
            options={
                'unique_together': {('etudiant', 'matiere', 'type_note', 'annee_universitaire', 'semestre')},
            },
        ),
    ]
