# Generated by Django 6.0.4 on 2026-05-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_enseignant_user_remove_etudiant_user_and_more'),
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='saisie_par',
            field=models.CharField(blank=True, help_text='Agent qui a saisi la note', max_length=100),
        ),
        migrations.AlterField(
            model_name='absence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='administration.etudiant'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.enseignant'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.salle'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='administration.filiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.enseignant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='administration.etudiant'),
        ),
    ]
