# Generated by Django 6.0.4 on 2026-05-04 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_inscription_options_remove_inscription_valide_and_more'),
        ('pedagogie', '0002_note_saisie_par_alter_absence_etudiant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emploidutemps',
            options={'ordering': ['jour', 'heure_debut']},
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='administration.classe'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='annee_universitaire',
            field=models.CharField(default='2024-2025', max_length=9),
        ),
        migrations.AlterField(
            model_name='note',
            name='saisie_par',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MoyenneEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_universitaire', models.CharField(default='2024-2025', max_length=9)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')], default=1)),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('mention', models.CharField(blank=True, choices=[('', '—'), ('passable', 'Passable (10–12)'), ('assez_bien', 'Assez Bien (12–14)'), ('bien', 'Bien (14–16)'), ('tres_bien', 'Très Bien (16–18)'), ('excellent', 'Excellent (18–20)')], max_length=20)),
                ('admis', models.BooleanField(default=False)),
                ('date_calcul', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='administration.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='administration.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'classe', 'annee_universitaire', 'semestre')},
            },
        ),
    ]
