# Generated by Django 6.0.4 on 2026-05-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.AddField(
            model_name='customuser',
            name='departement',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', 'Administrateur'), ('scolarite', 'Agent Scolarité'), ('chef_dept', 'Chef de Département'), ('doyen', 'Doyen / Vice-Doyen')], default='scolarite', max_length=20),
        ),
    ]
