# Generated by Django 6.0.4 on 2026-05-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_enseignant_user_remove_etudiant_user_and_more'),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandestage',
            name='commentaire_admin',
            field=models.TextField(blank=True, help_text="Commentaire interne de l'administration"),
        ),
        migrations.AlterField(
            model_name='demandestage',
            name='date_demande',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='demandestage',
            name='encadrant_fsb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_encadres', to='administration.enseignant'),
        ),
        migrations.AlterField(
            model_name='demandestage',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='administration.etudiant'),
        ),
        migrations.AlterField(
            model_name='demandestage',
            name='type_stage',
            field=models.CharField(choices=[('observation', 'Stage Observation'), ('initiation', 'Stage Initiation'), ('pfe', 'PFE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='administration.etudiant'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='mention',
            field=models.CharField(blank=True, choices=[('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien')], max_length=20),
        ),
    ]
