# Generated by Django 6.0.4 on 2026-05-01 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('pedagogie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_session', models.CharField(choices=[('principale', 'Principale'), ('rattrapage', 'Rattrapage')], max_length=15)),
                ('annee_universitaire', models.CharField(max_length=9)),
                ('semestre', models.IntegerField(choices=[(1, 'S1'), (2, 'S2')])),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlanningExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.salle')),
                ('surveillants', models.ManyToManyField(blank=True, to='administration.enseignant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.sessionexamen')),
            ],
        ),
        migrations.CreateModel(
            name='ResultatExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_exam', models.FloatField(blank=True, null=True)),
                ('note_ds', models.FloatField(blank=True, null=True)),
                ('note_tp', models.FloatField(blank=True, null=True)),
                ('note_finale', models.FloatField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.etudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedagogie.matiere')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examens.sessionexamen')),
            ],
            options={
                'unique_together': {('etudiant', 'session', 'matiere')},
            },
        ),
    ]
