# Generated by Django 6.0.4 on 2026-05-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_filiere_description_alter_filiere_niveau_and_more'),
        ('examens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planningexamen',
            options={'ordering': ['date', 'heure_debut']},
        ),
        migrations.AddField(
            model_name='planningexamen',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examens', to='administration.classe'),
        ),
        migrations.AlterField(
            model_name='planningexamen',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.salle'),
        ),
    ]
